# Generated by Django 3.0.6 on 2020-06-11 09:14

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('exampleapp', '0006_auto_20200611_0900'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='authors',
            field=jsonfield.fields.JSONField(blank=True, default='[]', verbose_name='authors'),
        ),
        migrations.AddField(
            model_name='post',
            name='notifications',
            field=jsonfield.fields.JSONField(blank=True, default='[]', verbose_name='notifications'),
        ),
    ]
