# Generated by Django 3.0.6 on 2020-06-11 10:05

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('exampleapp', '0007_auto_20200611_0914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='authors',
            field=jsonfield.fields.JSONField(blank=True, default=list, verbose_name='authors'),
        ),
        migrations.AlterField(
            model_name='post',
            name='average_note',
            field=models.FloatField(null=True, verbose_name='average_note'),
        ),
        migrations.AlterField(
            model_name='post',
            name='backlinks',
            field=jsonfield.fields.JSONField(blank=True, default=dict, verbose_name='backlinks'),
        ),
        migrations.AlterField(
            model_name='post',
            name='notifications',
            field=jsonfield.fields.JSONField(blank=True, default=list, verbose_name='notifications'),
        ),
    ]
